name: Create Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  creating-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Creating Pull Request
        uses: heitorpolidoro/autocreate-pr@v2
        env:
          <user>: ${{ secrets.<USER_PERSONAL_ACCESS_TOKEN> }}
